server:
  port: 80
knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # rewriteBatchedStatements参数置为true, 驱动才会帮你批量执行SQL
    url: jdbc:mysql://localhost:3306/delicious?serverTimezone=GMT%2B8&rewriteBatchedStatements=true
    username: root
    password: root
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 10
      # 最大连接池数量
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000

  resources:
    static-locations: classpath:static/,file:static/

  # 返回json的全局世界格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    # 配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启驼峰命名
    map-underscore-to-camel-case: true
  # 加载mapper目录下的所有xml文件
  mapper-locations: classpath:mapper/*.xml
  # 实体类别名,无需添加完整包路径
  type-aliases-package: com.example.entity
